GET http://localhost:3000/player


###


POST http://localhost:3000/playeradd/
Content-Type: application/json

{
    "name": "VIRAT",
    "age":32,
    "score": 157
}

###

PUT http://localhost:3000/update
Content-Type: application/json

{
"name": "uday"
}